// @generated Do not edit this file, which is automatically generated by the generator.

package dbschema

import (
	"fmt"

	"time"

	"github.com/webx-top/com"
	"github.com/webx-top/db"
	"github.com/webx-top/db/lib/factory"
	"github.com/webx-top/db/lib/factory/pagination"
	"github.com/webx-top/echo"
	"github.com/webx-top/echo/param"
)

type Slice_NgingVhost = factory.Slicex[*NgingVhost]

func NewNgingVhost(ctx echo.Context) *NgingVhost {
	m := &NgingVhost{}
	m.SetContext(ctx)
	return m
}

// NgingVhost 虚拟主机
type NgingVhost struct {
	base    factory.Base
	objects []*NgingVhost

	Id          uint   `db:"id,omitempty,pk" bson:"id,omitempty" comment:"ID" json:"id" xml:"id"`
	Name        string `db:"name" bson:"name" comment:"网站名称" json:"name" xml:"name"`
	GroupId     uint   `db:"group_id" bson:"group_id" comment:"组" json:"group_id" xml:"group_id"`
	Domain      string `db:"domain" bson:"domain" comment:"域名" json:"domain" xml:"domain"`
	Root        string `db:"root" bson:"root" comment:"网站物理路径" json:"root" xml:"root"`
	Created     uint   `db:"created" bson:"created" comment:"创建时间" json:"created" xml:"created" form_decoder:"time2unix" form_encoder:"unix2time"`
	Updated     uint   `db:"updated" bson:"updated" comment:"更新时间" json:"updated" xml:"updated" form_decoder:"time2unix" form_encoder:"unix2time"`
	Setting     string `db:"setting" bson:"setting" comment:"设置" json:"setting" xml:"setting"`
	Disabled    string `db:"disabled" bson:"disabled" comment:"是否停用" json:"disabled" xml:"disabled"`
	SslEnabled  string `db:"ssl_enabled" bson:"ssl_enabled" comment:"是否启用SSL(空值代表旧数据未记录)" json:"ssl_enabled" xml:"ssl_enabled"`
	SslObtained uint   `db:"ssl_obtained" bson:"ssl_obtained" comment:"SSL证书获取时间" json:"ssl_obtained" xml:"ssl_obtained"`
	SslRenewed  uint   `db:"ssl_renewed" bson:"ssl_renewed" comment:"SSL证书最近更新时间" json:"ssl_renewed" xml:"ssl_renewed"`
	ServerIdent string `db:"server_ident" bson:"server_ident" comment:"服务器标识" json:"server_ident" xml:"server_ident"`
}

// - base function

func (a *NgingVhost) Trans() factory.Transactioner {
	return a.base.Trans()
}

func (a *NgingVhost) Use(trans factory.Transactioner) factory.Model {
	a.base.Use(trans)
	return a
}

func (a *NgingVhost) SetContext(ctx echo.Context) factory.Model {
	a.base.SetContext(ctx)
	return a
}

func (a *NgingVhost) EventON(on ...bool) factory.Model {
	a.base.EventON(on...)
	return a
}

func (a *NgingVhost) EventOFF(off ...bool) factory.Model {
	a.base.EventOFF(off...)
	return a
}

func (a *NgingVhost) Context() echo.Context {
	return a.base.Context()
}

func (a *NgingVhost) SetConnID(connID int) factory.Model {
	a.base.SetConnID(connID)
	return a
}

func (a *NgingVhost) ConnID() int {
	return a.base.ConnID()
}

func (a *NgingVhost) SetNamer(namer func(factory.Model) string) factory.Model {
	a.base.SetNamer(namer)
	return a
}

func (a *NgingVhost) Namer() func(factory.Model) string {
	return a.base.Namer()
}

func (a *NgingVhost) SetParam(param *factory.Param) factory.Model {
	a.base.SetParam(param)
	return a
}

func (a *NgingVhost) Param(mw func(db.Result) db.Result, args ...interface{}) *factory.Param {
	if a.base.Param() == nil {
		return a.NewParam().SetMiddleware(mw).SetArgs(args...)
	}
	return a.base.Param().SetMiddleware(mw).SetArgs(args...)
}

func (a *NgingVhost) New(structName string, connID ...int) factory.Model {
	return a.base.New(structName, connID...)
}

func (a *NgingVhost) Base_() factory.Baser {
	return &a.base
}

// - current function

func (a *NgingVhost) Objects() []*NgingVhost {
	if a.objects == nil {
		return nil
	}
	return a.objects[:]
}

func (a *NgingVhost) XObjects() Slice_NgingVhost {
	return Slice_NgingVhost(a.Objects())
}

func (a *NgingVhost) NewObjects() factory.Ranger {
	return &Slice_NgingVhost{}
}

func (a *NgingVhost) InitObjects() *[]*NgingVhost {
	a.objects = []*NgingVhost{}
	return &a.objects
}

func (a *NgingVhost) NewParam() *factory.Param {
	return factory.NewParam(factory.DefaultFactory).SetIndex(a.base.ConnID()).SetTrans(a.base.Trans()).SetCollection(a.Name_()).SetModel(a)
}

func (a *NgingVhost) Short_() string {
	return "nging_vhost"
}

func (a *NgingVhost) Struct_() string {
	return "NgingVhost"
}

func (a *NgingVhost) Name_() string {
	b := a
	if b == nil {
		b = &NgingVhost{}
	}
	if b.base.Namer() != nil {
		return WithPrefix(b.base.Namer()(b))
	}
	return WithPrefix(factory.TableNamerGet(b.Short_())(b))
}

// CPAFrom Deprecated: Use CtxFrom instead.
func (a *NgingVhost) CPAFrom(source factory.Model) factory.Model {
	return a.CtxFrom(source)
}

func (a *NgingVhost) CtxFrom(source factory.Model) factory.Model {
	a.base.CtxFrom(source)
	return a
}

func (a *NgingVhost) Get(mw func(db.Result) db.Result, args ...interface{}) (err error) {
	base := a.base
	if !a.base.Eventable() {
		err = a.Param(mw, args...).SetRecv(a).One()
		a.base = base
		return
	}
	queryParam := a.Param(mw, args...).SetRecv(a)
	if err = a.base.FireReading(a, queryParam); err != nil {
		return
	}
	err = queryParam.One()
	a.base = base
	if err == nil {
		err = a.base.FireReaded(a, queryParam)
	}
	return
}

func (a *NgingVhost) List(recv interface{}, mw func(db.Result) db.Result, page, size int, args ...interface{}) (func() int64, error) {
	if recv == nil {
		recv = a.InitObjects()
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetPage(page).SetSize(size).SetRecv(recv).List()
	}
	queryParam := a.Param(mw, args...).SetPage(page).SetSize(size).SetRecv(recv)
	if err := a.base.FireReading(a, queryParam); err != nil {
		return nil, err
	}
	cnt, err := queryParam.List()
	if err == nil {
		switch v := recv.(type) {
		case *[]*NgingVhost:
			err = a.base.FireReaded(a, queryParam, Slice_NgingVhost(*v))
		case []*NgingVhost:
			err = a.base.FireReaded(a, queryParam, Slice_NgingVhost(v))
		case factory.Ranger:
			err = a.base.FireReaded(a, queryParam, v)
		}
	}
	return cnt, err
}

func (a *NgingVhost) GroupBy(keyField string, inputRows ...[]*NgingVhost) map[string][]*NgingVhost {
	var rows Slice_NgingVhost
	if len(inputRows) > 0 {
		rows = Slice_NgingVhost(inputRows[0])
	} else {
		rows = Slice_NgingVhost(a.Objects())
	}
	return rows.GroupBy(keyField)
}

func (a *NgingVhost) KeyBy(keyField string, inputRows ...[]*NgingVhost) map[string]*NgingVhost {
	var rows Slice_NgingVhost
	if len(inputRows) > 0 {
		rows = Slice_NgingVhost(inputRows[0])
	} else {
		rows = Slice_NgingVhost(a.Objects())
	}
	return rows.KeyBy(keyField)
}

func (a *NgingVhost) AsKV(keyField string, valueField string, inputRows ...[]*NgingVhost) param.Store {
	var rows Slice_NgingVhost
	if len(inputRows) > 0 {
		rows = Slice_NgingVhost(inputRows[0])
	} else {
		rows = Slice_NgingVhost(a.Objects())
	}
	return rows.AsKV(keyField, valueField)
}

func (a *NgingVhost) ListByOffset(recv interface{}, mw func(db.Result) db.Result, offset, size int, args ...interface{}) (func() int64, error) {
	if recv == nil {
		recv = a.InitObjects()
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetOffset(offset).SetSize(size).SetRecv(recv).List()
	}
	queryParam := a.Param(mw, args...).SetOffset(offset).SetSize(size).SetRecv(recv)
	if err := a.base.FireReading(a, queryParam); err != nil {
		return nil, err
	}
	cnt, err := queryParam.List()
	if err == nil {
		switch v := recv.(type) {
		case *[]*NgingVhost:
			err = a.base.FireReaded(a, queryParam, Slice_NgingVhost(*v))
		case []*NgingVhost:
			err = a.base.FireReaded(a, queryParam, Slice_NgingVhost(v))
		case factory.Ranger:
			err = a.base.FireReaded(a, queryParam, v)
		}
	}
	return cnt, err
}

func (a *NgingVhost) Insert() (pk interface{}, err error) {
	a.Created = uint(time.Now().Unix())
	a.Id = 0
	if len(a.Disabled) == 0 {
		a.Disabled = "N"
	}
	if len(a.ServerIdent) == 0 {
		a.ServerIdent = "default"
	}
	if a.base.Eventable() {
		err = a.base.Fire(factory.EventCreating, a, nil)
		if err != nil {
			return
		}
	}
	pk, err = a.Param(nil).SetSend(a).Insert()
	if err == nil && pk != nil {
		if v, y := pk.(uint); y {
			a.Id = v
		} else if v, y := pk.(int64); y {
			a.Id = uint(v)
		}
	}
	if err == nil && a.base.Eventable() {
		err = a.base.Fire(factory.EventCreated, a, nil)
	}
	return
}

func (a *NgingVhost) Update(mw func(db.Result) db.Result, args ...interface{}) (err error) {
	a.Updated = uint(time.Now().Unix())
	if len(a.Disabled) == 0 {
		a.Disabled = "N"
	}
	if len(a.ServerIdent) == 0 {
		a.ServerIdent = "default"
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(a).Update()
	}
	if err = a.base.Fire(factory.EventUpdating, a, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).SetSend(a).Update(); err != nil {
		return
	}
	return a.base.Fire(factory.EventUpdated, a, mw, args...)
}

func (a *NgingVhost) Updatex(mw func(db.Result) db.Result, args ...interface{}) (affected int64, err error) {
	a.Updated = uint(time.Now().Unix())
	if len(a.Disabled) == 0 {
		a.Disabled = "N"
	}
	if len(a.ServerIdent) == 0 {
		a.ServerIdent = "default"
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(a).Updatex()
	}
	if err = a.base.Fire(factory.EventUpdating, a, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).SetSend(a).Updatex(); err != nil {
		return
	}
	err = a.base.Fire(factory.EventUpdated, a, mw, args...)
	return
}

func (a *NgingVhost) UpdateByFields(mw func(db.Result) db.Result, fields []string, args ...interface{}) (err error) {
	a.Updated = uint(time.Now().Unix())
	if len(a.Disabled) == 0 {
		a.Disabled = "N"
	}
	if len(a.ServerIdent) == 0 {
		a.ServerIdent = "default"
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).UpdateByStruct(a, fields...)
	}
	editColumns := make([]string, len(fields))
	for index, field := range fields {
		editColumns[index] = com.SnakeCase(field)
	}
	if err = a.base.FireUpdate(factory.EventUpdating, a, editColumns, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).UpdateByStruct(a, fields...); err != nil {
		return
	}
	err = a.base.FireUpdate(factory.EventUpdated, a, editColumns, mw, args...)
	return
}

func (a *NgingVhost) UpdatexByFields(mw func(db.Result) db.Result, fields []string, args ...interface{}) (affected int64, err error) {
	a.Updated = uint(time.Now().Unix())
	if len(a.Disabled) == 0 {
		a.Disabled = "N"
	}
	if len(a.ServerIdent) == 0 {
		a.ServerIdent = "default"
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).UpdatexByStruct(a, fields...)
	}
	editColumns := make([]string, len(fields))
	for index, field := range fields {
		editColumns[index] = com.SnakeCase(field)
	}
	if err = a.base.FireUpdate(factory.EventUpdating, a, editColumns, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).UpdatexByStruct(a, fields...); err != nil {
		return
	}
	err = a.base.FireUpdate(factory.EventUpdated, a, editColumns, mw, args...)
	return
}

func (a *NgingVhost) UpdateField(mw func(db.Result) db.Result, field string, value interface{}, args ...interface{}) (err error) {
	return a.UpdateFields(mw, map[string]interface{}{
		field: value,
	}, args...)
}

func (a *NgingVhost) UpdatexField(mw func(db.Result) db.Result, field string, value interface{}, args ...interface{}) (affected int64, err error) {
	return a.UpdatexFields(mw, map[string]interface{}{
		field: value,
	}, args...)
}

func (a *NgingVhost) UpdateFields(mw func(db.Result) db.Result, kvset map[string]interface{}, args ...interface{}) (err error) {

	if val, ok := kvset["disabled"]; ok && val != nil {
		if v, ok := val.(string); ok && len(v) == 0 {
			kvset["disabled"] = "N"
		}
	}
	if val, ok := kvset["server_ident"]; ok && val != nil {
		if v, ok := val.(string); ok && len(v) == 0 {
			kvset["server_ident"] = "default"
		}
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(kvset).Update()
	}
	m := *a
	m.FromRow(kvset)
	editColumns := make([]string, 0, len(kvset))
	for column := range kvset {
		editColumns = append(editColumns, column)
	}
	if err = a.base.FireUpdate(factory.EventUpdating, &m, editColumns, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).SetSend(kvset).Update(); err != nil {
		return
	}
	return a.base.FireUpdate(factory.EventUpdated, &m, editColumns, mw, args...)
}

func (a *NgingVhost) UpdatexFields(mw func(db.Result) db.Result, kvset map[string]interface{}, args ...interface{}) (affected int64, err error) {

	if val, ok := kvset["disabled"]; ok && val != nil {
		if v, ok := val.(string); ok && len(v) == 0 {
			kvset["disabled"] = "N"
		}
	}
	if val, ok := kvset["server_ident"]; ok && val != nil {
		if v, ok := val.(string); ok && len(v) == 0 {
			kvset["server_ident"] = "default"
		}
	}
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(kvset).Updatex()
	}
	m := *a
	m.FromRow(kvset)
	editColumns := make([]string, 0, len(kvset))
	for column := range kvset {
		editColumns = append(editColumns, column)
	}
	if err = a.base.FireUpdate(factory.EventUpdating, &m, editColumns, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).SetSend(kvset).Updatex(); err != nil {
		return
	}
	err = a.base.FireUpdate(factory.EventUpdated, &m, editColumns, mw, args...)
	return
}

func (a *NgingVhost) UpdateValues(mw func(db.Result) db.Result, keysValues *db.KeysValues, args ...interface{}) (err error) {
	if !a.base.Eventable() {
		return a.Param(mw, args...).SetSend(keysValues).Update()
	}
	m := *a
	m.FromRow(keysValues.Map())
	if err = a.base.FireUpdate(factory.EventUpdating, &m, keysValues.Keys(), mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).SetSend(keysValues).Update(); err != nil {
		return
	}
	return a.base.FireUpdate(factory.EventUpdated, &m, keysValues.Keys(), mw, args...)
}

func (a *NgingVhost) Upsert(mw func(db.Result) db.Result, args ...interface{}) (pk interface{}, err error) {
	pk, err = a.Param(mw, args...).SetSend(a).Upsert(func() error {
		a.Updated = uint(time.Now().Unix())
		if len(a.Disabled) == 0 {
			a.Disabled = "N"
		}
		if len(a.ServerIdent) == 0 {
			a.ServerIdent = "default"
		}
		if !a.base.Eventable() {
			return nil
		}
		return a.base.Fire(factory.EventUpdating, a, mw, args...)
	}, func() error {
		a.Created = uint(time.Now().Unix())
		a.Id = 0
		if len(a.Disabled) == 0 {
			a.Disabled = "N"
		}
		if len(a.ServerIdent) == 0 {
			a.ServerIdent = "default"
		}
		if !a.base.Eventable() {
			return nil
		}
		return a.base.Fire(factory.EventCreating, a, nil)
	})
	if err == nil && pk != nil {
		if v, y := pk.(uint); y {
			a.Id = v
		} else if v, y := pk.(int64); y {
			a.Id = uint(v)
		}
	}
	if err == nil && a.base.Eventable() {
		if pk == nil {
			err = a.base.Fire(factory.EventUpdated, a, mw, args...)
		} else {
			err = a.base.Fire(factory.EventCreated, a, nil)
		}
	}
	return
}

func (a *NgingVhost) Delete(mw func(db.Result) db.Result, args ...interface{}) (err error) {

	if !a.base.Eventable() {
		return a.Param(mw, args...).Delete()
	}
	if err = a.base.Fire(factory.EventDeleting, a, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).Delete(); err != nil {
		return
	}
	return a.base.Fire(factory.EventDeleted, a, mw, args...)
}

func (a *NgingVhost) Deletex(mw func(db.Result) db.Result, args ...interface{}) (affected int64, err error) {

	if !a.base.Eventable() {
		return a.Param(mw, args...).Deletex()
	}
	if err = a.base.Fire(factory.EventDeleting, a, mw, args...); err != nil {
		return
	}
	if affected, err = a.Param(mw, args...).Deletex(); err != nil {
		return
	}
	err = a.base.Fire(factory.EventDeleted, a, mw, args...)
	return
}

func (a *NgingVhost) Count(mw func(db.Result) db.Result, args ...interface{}) (int64, error) {
	return a.Param(mw, args...).Count()
}

func (a *NgingVhost) Exists(mw func(db.Result) db.Result, args ...interface{}) (bool, error) {
	return a.Param(mw, args...).Exists()
}

func (a *NgingVhost) Reset() *NgingVhost {
	a.Id = 0
	a.Name = ``
	a.GroupId = 0
	a.Domain = ``
	a.Root = ``
	a.Created = 0
	a.Updated = 0
	a.Setting = ``
	a.Disabled = ``
	a.SslEnabled = ``
	a.SslObtained = 0
	a.SslRenewed = 0
	a.ServerIdent = ``
	return a
}

func (a *NgingVhost) AsMap(onlyFields ...string) param.Store {
	r := param.Store{}
	if len(onlyFields) == 0 {
		r["Id"] = a.Id
		r["Name"] = a.Name
		r["GroupId"] = a.GroupId
		r["Domain"] = a.Domain
		r["Root"] = a.Root
		r["Created"] = a.Created
		r["Updated"] = a.Updated
		r["Setting"] = a.Setting
		r["Disabled"] = a.Disabled
		r["SslEnabled"] = a.SslEnabled
		r["SslObtained"] = a.SslObtained
		r["SslRenewed"] = a.SslRenewed
		r["ServerIdent"] = a.ServerIdent
		return r
	}
	for _, field := range onlyFields {
		switch field {
		case "Id":
			r["Id"] = a.Id
		case "Name":
			r["Name"] = a.Name
		case "GroupId":
			r["GroupId"] = a.GroupId
		case "Domain":
			r["Domain"] = a.Domain
		case "Root":
			r["Root"] = a.Root
		case "Created":
			r["Created"] = a.Created
		case "Updated":
			r["Updated"] = a.Updated
		case "Setting":
			r["Setting"] = a.Setting
		case "Disabled":
			r["Disabled"] = a.Disabled
		case "SslEnabled":
			r["SslEnabled"] = a.SslEnabled
		case "SslObtained":
			r["SslObtained"] = a.SslObtained
		case "SslRenewed":
			r["SslRenewed"] = a.SslRenewed
		case "ServerIdent":
			r["ServerIdent"] = a.ServerIdent
		}
	}
	return r
}

func (a *NgingVhost) Clone() *NgingVhost {
	cloned := NgingVhost{Id: a.Id, Name: a.Name, GroupId: a.GroupId, Domain: a.Domain, Root: a.Root, Created: a.Created, Updated: a.Updated, Setting: a.Setting, Disabled: a.Disabled, SslEnabled: a.SslEnabled, SslObtained: a.SslObtained, SslRenewed: a.SslRenewed, ServerIdent: a.ServerIdent}
	cloned.CtxFrom(a)
	return &cloned
}

func (a *NgingVhost) FromRow(row map[string]interface{}) {
	for key, value := range row {
		if _, ok := value.(db.RawValue); ok {
			continue
		}
		switch key {
		case "id":
			a.Id = param.AsUint(value)
		case "name":
			a.Name = param.AsString(value)
		case "group_id":
			a.GroupId = param.AsUint(value)
		case "domain":
			a.Domain = param.AsString(value)
		case "root":
			a.Root = param.AsString(value)
		case "created":
			a.Created = param.AsUint(value)
		case "updated":
			a.Updated = param.AsUint(value)
		case "setting":
			a.Setting = param.AsString(value)
		case "disabled":
			a.Disabled = param.AsString(value)
		case "ssl_enabled":
			a.SslEnabled = param.AsString(value)
		case "ssl_obtained":
			a.SslObtained = param.AsUint(value)
		case "ssl_renewed":
			a.SslRenewed = param.AsUint(value)
		case "server_ident":
			a.ServerIdent = param.AsString(value)
		}
	}
}

func (a *NgingVhost) GetField(field string) interface{} {
	switch field {
	case "Id":
		return a.Id
	case "Name":
		return a.Name
	case "GroupId":
		return a.GroupId
	case "Domain":
		return a.Domain
	case "Root":
		return a.Root
	case "Created":
		return a.Created
	case "Updated":
		return a.Updated
	case "Setting":
		return a.Setting
	case "Disabled":
		return a.Disabled
	case "SslEnabled":
		return a.SslEnabled
	case "SslObtained":
		return a.SslObtained
	case "SslRenewed":
		return a.SslRenewed
	case "ServerIdent":
		return a.ServerIdent
	default:
		return nil
	}
}

func (a *NgingVhost) GetAllFieldNames() []string {
	return []string{
		"Id",
		"Name",
		"GroupId",
		"Domain",
		"Root",
		"Created",
		"Updated",
		"Setting",
		"Disabled",
		"SslEnabled",
		"SslObtained",
		"SslRenewed",
		"ServerIdent",
	}
}

func (a *NgingVhost) HasField(field string) bool {
	switch field {
	case "Id":
		return true
	case "Name":
		return true
	case "GroupId":
		return true
	case "Domain":
		return true
	case "Root":
		return true
	case "Created":
		return true
	case "Updated":
		return true
	case "Setting":
		return true
	case "Disabled":
		return true
	case "SslEnabled":
		return true
	case "SslObtained":
		return true
	case "SslRenewed":
		return true
	case "ServerIdent":
		return true
	default:
		return false
	}
}

func (a *NgingVhost) Set(key interface{}, value ...interface{}) {
	switch k := key.(type) {
	case map[string]interface{}:
		for kk, vv := range k {
			a.Set(kk, vv)
		}
	default:
		var (
			kk string
			vv interface{}
		)
		if k, y := key.(string); y {
			kk = k
		} else {
			kk = fmt.Sprint(key)
		}
		if len(value) > 0 {
			vv = value[0]
		}
		switch kk {
		case "Id":
			a.Id = param.AsUint(vv)
		case "Name":
			a.Name = param.AsString(vv)
		case "GroupId":
			a.GroupId = param.AsUint(vv)
		case "Domain":
			a.Domain = param.AsString(vv)
		case "Root":
			a.Root = param.AsString(vv)
		case "Created":
			a.Created = param.AsUint(vv)
		case "Updated":
			a.Updated = param.AsUint(vv)
		case "Setting":
			a.Setting = param.AsString(vv)
		case "Disabled":
			a.Disabled = param.AsString(vv)
		case "SslEnabled":
			a.SslEnabled = param.AsString(vv)
		case "SslObtained":
			a.SslObtained = param.AsUint(vv)
		case "SslRenewed":
			a.SslRenewed = param.AsUint(vv)
		case "ServerIdent":
			a.ServerIdent = param.AsString(vv)
		}
	}
}

func (a *NgingVhost) AsRow(onlyFields ...string) param.Store {
	r := param.Store{}
	if len(onlyFields) == 0 {
		r["id"] = a.Id
		r["name"] = a.Name
		r["group_id"] = a.GroupId
		r["domain"] = a.Domain
		r["root"] = a.Root
		r["created"] = a.Created
		r["updated"] = a.Updated
		r["setting"] = a.Setting
		r["disabled"] = a.Disabled
		r["ssl_enabled"] = a.SslEnabled
		r["ssl_obtained"] = a.SslObtained
		r["ssl_renewed"] = a.SslRenewed
		r["server_ident"] = a.ServerIdent
		return r
	}
	for _, field := range onlyFields {
		switch field {
		case "id":
			r["id"] = a.Id
		case "name":
			r["name"] = a.Name
		case "group_id":
			r["group_id"] = a.GroupId
		case "domain":
			r["domain"] = a.Domain
		case "root":
			r["root"] = a.Root
		case "created":
			r["created"] = a.Created
		case "updated":
			r["updated"] = a.Updated
		case "setting":
			r["setting"] = a.Setting
		case "disabled":
			r["disabled"] = a.Disabled
		case "ssl_enabled":
			r["ssl_enabled"] = a.SslEnabled
		case "ssl_obtained":
			r["ssl_obtained"] = a.SslObtained
		case "ssl_renewed":
			r["ssl_renewed"] = a.SslRenewed
		case "server_ident":
			r["server_ident"] = a.ServerIdent
		}
	}
	return r
}

func (a *NgingVhost) ListPage(cond *db.Compounds, sorts ...interface{}) error {
	return pagination.ListPage(a, cond, sorts...)
}

func (a *NgingVhost) ListPageAs(recv interface{}, cond *db.Compounds, sorts ...interface{}) error {
	return pagination.ListPageAs(a, recv, cond, sorts...)
}

func (a *NgingVhost) ListPageByOffset(cond *db.Compounds, sorts ...interface{}) error {
	return pagination.ListPageByOffset(a, cond, sorts...)
}

func (a *NgingVhost) ListPageByOffsetAs(recv interface{}, cond *db.Compounds, sorts ...interface{}) error {
	return pagination.ListPageByOffsetAs(a, recv, cond, sorts...)
}

func (a *NgingVhost) BatchValidate(kvset map[string]interface{}) error {
	return a.base.BatchValidate(a, kvset)
}

func (a *NgingVhost) Validate(column string, value interface{}) error {
	return a.base.Validate(a, column, value)
}

func (a *NgingVhost) TrimOverflowText(column string, value string) string {
	return a.base.TrimOverflowText(a, column, value)
}
